name: Generate Android Upload Key

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair \
            -keystore upload-key.jks \
            -storepass "November@13" \
            -keypass "November@13" \
            -alias "faav11_" \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -dname "CN=faav11_, OU=Development, O=faav11, L=agbor, ST=delta, C=NG"

      - name: Export Upload Certificate
        run: |
          keytool -export -rfc \
            -keystore upload-key.jks \
            -storepass "November@13" \
            -alias "faav11_" \
            -file upload_certificate.pem

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android-upload-key
          path: |
            upload-key.jks
            upload_certificate.pem
